/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform statistics */
        get: operations["getStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets/featured": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List featured markets */
        get: operations["getFeaturedMarkets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Paginated content feed */
        get: operations["getContent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/markets/{market_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resolve a market and invalidate caches (admin) */
        post: operations["resolveMarket"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blockchain/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Blockchain node and contract health
         * @description Returns the health of the blockchain node and contract.
         *
         *     **`status` values:**
         *     - `healthy` – node reachable and contract readable. HTTP 200.
         *     - `degraded` – node reachable but contract read failed. HTTP 503.
         *     - `unhealthy` – node unreachable. HTTP 503.
         *
         *     `is_healthy` is `true` only when `status == "healthy"` (backwards-compatible field).
         */
        get: operations["getBlockchainHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blockchain/markets/{market_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** On-chain market data */
        get: operations["getBlockchainMarket"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blockchain/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Platform on-chain statistics */
        get: operations["getBlockchainStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blockchain/users/{user}/bets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Bets placed by a user */
        get: operations["getUserBets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blockchain/oracle/{market_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Oracle result for a market */
        get: operations["getOracleResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/blockchain/tx/{tx_hash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Transaction status by hash */
        get: operations["getTransactionStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/newsletter/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe to newsletter */
        post: operations["newsletterSubscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/newsletter/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Confirm newsletter subscription via token */
        get: operations["newsletterConfirm"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/newsletter/unsubscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Unsubscribe from newsletter */
        delete: operations["newsletterUnsubscribe"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/newsletter/gdpr/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GDPR data export for a subscriber */
        get: operations["newsletterGdprExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/newsletter/gdpr/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** GDPR data deletion for a subscriber */
        delete: operations["newsletterGdprDelete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email/preview/{template_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview a rendered email template (admin) */
        get: operations["emailPreview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Send a test email (admin) */
        post: operations["emailSendTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Email analytics (admin) */
        get: operations["getEmailAnalytics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email/queue/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Email queue statistics (admin) */
        get: operations["getEmailQueueStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blockchain/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay blockchain events (admin) */
        post: operations["blockchainReplay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email/queue/dead-letter": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List dead-letter email jobs (admin) */
        get: operations["getEmailDeadLetterList"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/email/queue/dead-letter/{job_id}/requeue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Requeue a dead-letter email job (admin) */
        post: operations["requeueEmailDeadLetterJob"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve audit log entries (admin) */
        get: operations["getAuditLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/audit/statistics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieve audit event statistics (admin) */
        get: operations["getAuditStatistics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/sendgrid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * SendGrid event webhook receiver (provider-signed)
         * @description Receives webhook events from SendGrid for email delivery, bounce, complaint,
         *     and engagement tracking (opens, clicks, unsubscribes).
         *
         *     ## Security Model
         *
         *     This endpoint uses **provider signature verification** (not API key authentication).
         *
         *     - **Authentication**: HMAC-SHA256 signature in `X-Twilio-Email-Event-Webhook-Signature` header
         *     - **Timestamp verification**: `X-Twilio-Email-Event-Webhook-Timestamp` must be within 300 seconds
         *     - **Replay protection**: Checked per (message_id, event_type, recipient, timestamp)
         *
         *     This security model is appropriate for webhooks because:
         *     1. SendGrid is the only caller (not user-initiated)
         *     2. Signature proves the provider encrypted the request
         *     3. No need for per-user API keys on public-facing webhook endpoints
         */
        post: operations["sendgridWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnyObject: {
            [key: string]: unknown;
        };
        BlockchainHealth: {
            network: string;
            rpc_url: string;
            latest_ledger: number;
            /**
             * @description healthy = node + contract OK; degraded = node OK but contract unreadable; unhealthy = node unreachable
             * @enum {string}
             */
            status: "healthy" | "degraded" | "unhealthy";
            /** @description true only when status is healthy (backwards-compatible) */
            is_healthy: boolean;
            contract_reachable: boolean;
            checked_at_unix: number;
            /** @enum {string} */
            data_source: "live" | "stale_cache" | "rpc_fallback";
        };
        ApiError: {
            /**
             * @description Machine-readable error code
             * @example INTERNAL_ERROR
             */
            code: string;
            /** @description Human-readable error description */
            message: string;
            /** @description Optional additional context about the error */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        FeaturedMarketView: {
            /** Format: int64 */
            id: number;
            title: string;
            /** Format: double */
            volume: number;
            /** Format: date-time */
            ends_at: string;
            onchain_volume: string;
            /** Format: int32 */
            resolved_outcome?: number | null;
        };
        InvalidationResult: {
            invalidated_keys: number;
        };
        NewsletterSubscribeRequest: {
            /** Format: email */
            email: string;
            source?: string;
        };
        EmailRequest: {
            /** Format: email */
            email: string;
        };
        NewsletterResponse: {
            success: boolean;
            message: string;
        };
        NewsletterExportResponse: {
            success: boolean;
            data: components["schemas"]["AnyObject"];
        };
        EmailTestRequest: {
            /** Format: email */
            recipient: string;
            template_name: string;
        };
        EmailTestResponse: {
            success: boolean;
            message: string;
            message_id: string;
        };
    };
    responses: {
        /** @description Error response with machine-readable code */
        ApiError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiError"];
            };
        };
        /** @description Newsletter operation result */
        NewsletterResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["NewsletterResponse"];
            };
        };
    };
    parameters: {
        /**
         * @description Target API version. Defaults to the current stable version (`v1`).
         *     Responses for deprecated versions include `Deprecation`, `Sunset`, and `Link` headers.
         */
        apiVersion: "v1";
        /**
         * @description Client-generated unique key (e.g. UUID v4) to deduplicate mutating requests.
         *     If a request with the same key was processed within the idempotency window,
         *     the cached response is returned immediately without re-executing the operation.
         */
        idempotencyKey: string;
        marketId: number;
        page: number;
        pageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": string;
                };
            };
            500: components["responses"]["ApiError"];
        };
    };
    getStatistics: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Target API version. Defaults to the current stable version (`v1`).
                 *     Responses for deprecated versions include `Deprecation`, `Sunset`, and `Link` headers.
                 */
                "API-Version"?: components["parameters"]["apiVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Statistics payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getFeaturedMarkets: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Target API version. Defaults to the current stable version (`v1`).
                 *     Responses for deprecated versions include `Deprecation`, `Sunset`, and `Link` headers.
                 */
                "API-Version"?: components["parameters"]["apiVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Array of featured markets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FeaturedMarketView"][];
                };
            };
            400: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getContent: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
            };
            header?: {
                /**
                 * @description Target API version. Defaults to the current stable version (`v1`).
                 *     Responses for deprecated versions include `Deprecation`, `Sunset`, and `Link` headers.
                 */
                "API-Version"?: components["parameters"]["apiVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Content payload */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    resolveMarket: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Target API version. Defaults to the current stable version (`v1`).
                 *     Responses for deprecated versions include `Deprecation`, `Sunset`, and `Link` headers.
                 */
                "API-Version"?: components["parameters"]["apiVersion"];
            };
            path: {
                market_id: components["parameters"]["marketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cache invalidation result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidationResult"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            404: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getBlockchainHealth: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Target API version. Defaults to the current stable version (`v1`).
                 *     Responses for deprecated versions include `Deprecation`, `Sunset`, and `Link` headers.
                 */
                "API-Version"?: components["parameters"]["apiVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Node and contract are healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockchainHealth"];
                };
            };
            400: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
            /** @description Degraded (node up, contract unreachable) or unhealthy (node down) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlockchainHealth"];
                };
            };
        };
    };
    getBlockchainMarket: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Target API version. Defaults to the current stable version (`v1`).
                 *     Responses for deprecated versions include `Deprecation`, `Sunset`, and `Link` headers.
                 */
                "API-Version"?: components["parameters"]["apiVersion"];
            };
            path: {
                market_id: components["parameters"]["marketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Market chain data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            404: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getBlockchainStats: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Target API version. Defaults to the current stable version (`v1`).
                 *     Responses for deprecated versions include `Deprecation`, `Sunset`, and `Link` headers.
                 */
                "API-Version"?: components["parameters"]["apiVersion"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Platform stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getUserBets: {
        parameters: {
            query?: {
                page?: components["parameters"]["page"];
                page_size?: components["parameters"]["pageSize"];
            };
            header?: {
                /**
                 * @description Target API version. Defaults to the current stable version (`v1`).
                 *     Responses for deprecated versions include `Deprecation`, `Sunset`, and `Link` headers.
                 */
                "API-Version"?: components["parameters"]["apiVersion"];
            };
            path: {
                /** @description Stellar address of the user */
                user: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User bets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            404: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getOracleResult: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Target API version. Defaults to the current stable version (`v1`).
                 *     Responses for deprecated versions include `Deprecation`, `Sunset`, and `Link` headers.
                 */
                "API-Version"?: components["parameters"]["apiVersion"];
            };
            path: {
                market_id: components["parameters"]["marketId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Oracle result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            404: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getTransactionStatus: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Target API version. Defaults to the current stable version (`v1`).
                 *     Responses for deprecated versions include `Deprecation`, `Sunset`, and `Link` headers.
                 */
                "API-Version"?: components["parameters"]["apiVersion"];
            };
            path: {
                tx_hash: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Transaction status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            404: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    newsletterSubscribe: {
        parameters: {
            query?: never;
            header?: {
                /**
                 * @description Target API version. Defaults to the current stable version (`v1`).
                 *     Responses for deprecated versions include `Deprecation`, `Sunset`, and `Link` headers.
                 */
                "API-Version"?: components["parameters"]["apiVersion"];
                /**
                 * @description Client-generated unique key (e.g. UUID v4) to deduplicate mutating requests.
                 *     If a request with the same key was processed within the idempotency window,
                 *     the cached response is returned immediately without re-executing the operation.
                 */
                "Idempotency-Key"?: components["parameters"]["idempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewsletterSubscribeRequest"];
            };
        };
        responses: {
            200: components["responses"]["NewsletterResponse"];
            400: components["responses"]["NewsletterResponse"];
            409: components["responses"]["NewsletterResponse"];
            429: components["responses"]["NewsletterResponse"];
            500: components["responses"]["ApiError"];
        };
    };
    newsletterConfirm: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["NewsletterResponse"];
            400: components["responses"]["NewsletterResponse"];
            404: components["responses"]["NewsletterResponse"];
            500: components["responses"]["ApiError"];
        };
    };
    newsletterUnsubscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            200: components["responses"]["NewsletterResponse"];
            400: components["responses"]["NewsletterResponse"];
            404: components["responses"]["NewsletterResponse"];
            500: components["responses"]["ApiError"];
        };
    };
    newsletterGdprExport: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Subscriber data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsletterExportResponse"];
                };
            };
            400: components["responses"]["NewsletterResponse"];
            404: components["responses"]["NewsletterResponse"];
            500: components["responses"]["ApiError"];
        };
    };
    newsletterGdprDelete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            200: components["responses"]["NewsletterResponse"];
            400: components["responses"]["NewsletterResponse"];
            404: components["responses"]["NewsletterResponse"];
            500: components["responses"]["ApiError"];
        };
    };
    emailPreview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_name: "newsletter_confirmation" | "waitlist_confirmation" | "contact_form_auto_response" | "welcome_email";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rendered email preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            404: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    emailSendTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailTestRequest"];
            };
        };
        responses: {
            /** @description Test email result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EmailTestResponse"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getEmailAnalytics: {
        parameters: {
            query?: {
                template_name?: string;
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Analytics data */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getEmailQueueStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Queue stats */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    blockchainReplay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replay result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getEmailDeadLetterList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Dead-letter job list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    requeueEmailDeadLetterJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Dead-letter job identifier */
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Requeue result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            404: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getAuditLogs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit log entries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    getAuditStatistics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit statistics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnyObject"];
                };
            };
            400: components["responses"]["ApiError"];
            401: components["responses"]["ApiError"];
            403: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
    sendgridWebhook: {
        parameters: {
            query?: never;
            header: {
                /** @description HMAC-SHA256 signature of timestamp+body, base64-encoded. Signature is computed as Base64(HMAC-SHA256(secret, timestamp+body)) */
                "X-Twilio-Email-Event-Webhook-Signature": string;
                /** @description Unix timestamp of the request (replay protection window is 300 seconds) */
                "X-Twilio-Email-Event-Webhook-Timestamp": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnyObject"][];
            };
        };
        responses: {
            /** @description Webhook processed successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @description Number of events processed */
                        processed?: number;
                        /** @description List of processing errors, if any */
                        errors?: string[] | null;
                    };
                };
            };
            /** @description Invalid request or signature */
            400: components["responses"]["ApiError"];
            /** @description Signature verification failed (not authorized as SendGrid) */
            401: components["responses"]["ApiError"];
            429: components["responses"]["ApiError"];
            500: components["responses"]["ApiError"];
        };
    };
}
